# Base the image on python
FROM quay.io/openshiftio/che-centos_python

# Basic system hygiene
RUN sudo yum -y update && \
#    sudo yum -y upgrade && \

# Enable python and install pygame
    source /opt/rh/rh-python36/enable && \
    sudo PATH=/opt/rh/rh-python36/root/usr/bin${PATH} LD_LIBRARY_PATH=/opt/rh/rh-python36/root/usr/lib64 MANPATH=/opt/rh/rh-python36/root/usr/share/man:${MANPATH} PKG_CONFIG_PATH=/opt/rh/rh-python36/root/usr/lib64/pkgconfig XDG_DATA_DIRS=/opt/rh/rh-python36/root/usr/share:${XDG_DATA_DIRS} /opt/rh/rh-python36/root/usr/bin/pip install pygame && \

# Configure git
    git config --global user.name "Sanjay Aiyagari" && \
    git config --global user.email ska1@cornell.edu

# IMPORTANT: The Dockerfile has to end with a non-terminating CMD. This works
# as well as any....
CMD tail -f /dev/null 
